apiVersion: v1
kind: Service
metadata:
  name: vectordb
spec:
  ports:
  - port: 8000
    name: http
  clusterIP: None
  selector:
    app: vectordb
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-leader
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: vectordb
    leader: "true"